
classDiagram
    class Program
    Program: +CreateHostBuilder()
    Program ..> StartUp : create

    class StartUp
    StartUp ..> BCWebApiServiceCollectionExtension : uses
    StartUp ..> AppSession : creates
    StartUp: -HttpClient _client
    StartUp: +ConfigureService(IServiceCollection services)
    StartUp: +Configure(IApplicationBuilder app, IWebHostEnvironment env)

    class IAuthenticationService
    <<interface>> IAuthenticationService
    IAuthenticationService: Get() Task~AuthenticationHeaderValue~

    class ICompaniesService
    <<interface>> ICompaniesService
    ICompaniesService: GetCompanies() Task~CompaniesServiceResponse~
    ICompaniesService: GetCompanyName(string companyId) Task~string~

    class ICredentialsService
    <<interface>> ICredentialsService
    ICredentialsService: GetCredentials(String Username, string companyID) Task~CredentialsServiceResponse~

    class IJobPlanningLineService
    <<interface>> IJobPlanningLineService
    IJobPlanningLineService: GetPlanningLines(string companyID, string jobNo, string jobTaskNo) Task~JobPlanningLinesModelResponse~

    class IJobService
    <<interface>> IJobService
    IJobService: GetJobs(string companyID, string username) Task~JobModelResponse~
    IJobService: GetFavJobsAsync(string companyID, string username) Task~FavJobsModelResponse~
    IJobService: PostFavJobAsync(FavJobModel request, string companyID)
    IJobService: DeleteFavJobsAsync(string id, string username, string companyID)

    class IJobTasksService
    <<interface>> IJobTasksService
    IJobTasksService: GetTasks(string companyID, string jobNo) Task~JobTasksModelResponse~

    class ILocalTimeService
    <<interface>> ILocalTimeService
    ILocalTimeService: GetLocalDateTime() DateTime
    ILocalTimeService: CalculateUTCDateTime(DateTime LocalDate) DateTime

    class ITimeRecordingsService
    <<interface>> ITimeRecordingsService
    ITimeRecordingsService: GetTimeRecordings(string companyID, string username) Task~TimeRecordingResponse~
    ITimeRecordingsService: PostTimeRecording(TimeRecording request, string companyID, int timezoneOffset) 
    ITimeRecordingsService: PatchTimeRecording(TimeRecording request, string companyID) 
    ITimeRecordingsService: DeleteTimeRecordings(int id, string companyID) 
    ITimeRecordingsService: GetUnstopped(string companyID, string username) Task~TimeRecording~
    ITimeRecordingsService: GetUnstoppedPause(string companyID, string username) Task~TimeRecording~
    ITimeRecordingsService: GetAllTimeRecordings(string companyID, string username) Task~TimeRecordingResponse~
    ITimeRecordingsService: GetTodayTimeRecordings(string companyID, string username) Task~TimeRecordingResponse~

    class ITypeOfAbsentDaysService
    <<interface>> ITypeOfAbsentDaysService
    ITypeOfAbsentDaysService: GetTypeOfAbsentDays(string companyID) Task~TypeOfAbsentDaysResponse~


    class AuthenticationBaseService
    AuthenticationBaseService ..> IAuthenticationService
    AuthenticationBaseService: -IConfiguration _config

    class BasicAuthService
    BasicAuthService --|> AuthenticationBaseService
    BasicAuthService: +Get() Task~AuthenticationHeaderValue~

    class OAuthService
    OAuthService --|> AuthenticationBaseService
    OAuthService: -AuthenticationResult AuthResult
    OAuthService: +Get() Task~AuthenticationHeaderValue~
    OAuthService: -GetNewAccessToken() Task~AuthenticationResult~

    class CompaniesService
    CompaniesService ..> ICompaniesService
    CompaniesService ..> IAuthenticationService
    CompaniesService ..> Company: create
    CompaniesService ..> CompaniesServiceResponse: create
    CompaniesService: -string _baseURL
    CompaniesService: -string _apiEndpoint
    CompaniesService: -HttpClient client
    CompaniesService: -IAuthenticationService _authenticationService

    class CredentialsService
    CredentialsService ..> ICredentialsService
    CredentialsService ..> IAuthenticationService
    CredentialsService ..> CredentialsServiceResponse: create
    CredentialsService: -string _baseURL
    CredentialsService: -string _apiEndpoint
    CredentialsService: -HttpClient client
    CredentialsService: -IAuthenticationService _authenticationService

    class JobPlanningLineService
    JobPlanningLineService ..> IJobPlanningLineService
    JobPlanningLineService ..> IAuthenticationService
    JobPlanningLineService ..> JobPlanningLinesModelResponse: create
    JobPlanningLineService ..> JobPlanningLinesModel: create
    JobPlanningLineService: -string _baseURL
    JobPlanningLineService: -string _apiEndpointGet
    JobPlanningLineService: -string _apiEndpointGetWithParameter
    JobPlanningLineService: -HttpClient client
    JobPlanningLineService: -IAuthenticationService _authenticationService

    class JobService
    JobService ..> IJobService
    JobService ..> IAuthenticationService
    JobService ..> JobModelResponse: create
    JobService ..> JobModel: create
    JobService ..> FavJobsModelResponse: create
    JobService ..> FavJobModel: create
    JobService: -string _baseURL
    JobService: -string _apiEndpointGet
    JobService: -string _apiEndpointGetFav
    JobService: -string _apiEndpointSetFav
    JobService: -HttpClient client
    JobService: -IAuthenticationService _authenticationService

    class JobTasksService
    JobTasksService ..> IJobTasksService
    JobTasksService ..> IAuthenticationService
    JobTasksService ..> JobTasksModelResponse: create
    JobTasksService ..> JobTasksModel: create
    JobTasksService: -string _baseURL
    JobTasksService: -string _apiEndpointGet
    JobTasksService: -HttpClient client
    JobTasksService: -IAuthenticationService _authenticationService

    class LocalTimeService
    LocalTimeService ..> ILocalTimeService
    LocalTimeService: -int TimeZoneOffset
    LocalTimeService: -IHttpContextAccessor _httpContextAccessor
    LocalTimeService: -GetTimeZoneOffset()

    class TimeRecordingsService
    TimeRecordingsService ..> ITimeRecordingsService
    TimeRecordingsService ..> IAuthenticationService
    TimeRecordingsService ..> ILocalTimeService
    TimeRecordingsService ..> TimeRecordingResponse: create
    TimeRecordingsService ..> TimeRecording: create
    TimeRecordingsService: -string _baseURL
    TimeRecordingsService: -string _apiEndpointGet
    TimeRecordingsService: -string _apiEndpointSet
    TimeRecordingsService: -string _apiEndpointGetToday
    TimeRecordingsService: -string _apiEndpointUnstopped
    TimeRecordingsService: -string _apiEndpointUnstoppedPause
    TimeRecordingsService: -HttpClient client
    TimeRecordingsService: -IAuthenticationService _authenticationService
    TimeRecordingsService: -ILocalTimeService _localTimeService
    TimeRecordingsService: -GetDates(String companyID, string username) Task~String~

    class TypeOfAbsentDaysService
    TypeOfAbsentDaysService ..> ITypeOfAbsentDaysService
    TypeOfAbsentDaysService ..> IAuthenticationService
    TypeOfAbsentDaysService ..> TypeOfAbsentDaysResponse: create
    TypeOfAbsentDaysService ..> TypeOfAbsentDays: create
    TypeOfAbsentDaysService: -string _baseURL
    TypeOfAbsentDaysService: -string _apiEndpointGet
    TypeOfAbsentDaysService: -HttpClient client
    TypeOfAbsentDaysService: -IAuthenticationService _authenticationService

    class BCWebApiServiceCollectionExtension
    BCWebApiServiceCollectionExtension: +AddBCWebApiServices(this IServiceCollection services)
    BCWebApiServiceCollectionExtension: -AddBCWebApiAuthenticationService(this IServiceCollection services)

    class AppSession
    AppSession: +ISession Session
    AppSession: +string ContactNo
    AppSession: +string CompanyID
    AppSession: +string sessionToken
    AppSession: +int timeZoneOffset
    AppSession: +Clear()
    AppSession: +Check() Boolean

    class JobPlanningLinesController
    JobPlanningLinesController ..> IJobPlanningLineService
    JobPlanningLinesController ..> AppSession
    JobPlanningLinesController ..> JobPlanningLinesModelResponse: create
    JobPlanningLinesController: -IJobPlanningLineService _jobPlanningLineService
    JobPlanningLinesController: -AppSession _appSession
    JobPlanningLinesController: +Index(Taskparameter param) Task<JobPlanningLinesModelResponse>

    class JobTasksController
    JobTasksController ..> IJobTasksService
    JobTasksController ..> AppSession
    JobTasksController ..> JobTasksModelResponse: create
    JobTasksController: -IJobTasksService _jobTasksService
    JobTasksController: -AppSession _appSession
    JobTasksController: +Index(Taskparameter param) Task<JobTasksModelResponse>

    class TimeRecordingsController
    TimeRecordingsController ..> ITimeRecordingsService
    TimeRecordingsController ..> AppSession
    TimeRecordingsController ..> TimeRecordingResponse: create
    TimeRecordingsController: -ITimeRecordingsService _timeRecordingsService
    TimeRecordingsController: -AppSession _appSession
    TimeRecordingsController: +Index(Taskparameter param) Task<TimeRecordingResponse>

    class Company
    Company: +Guid Id
    Company: +string Name

    class CompaniesServiceResponse
    CompaniesServiceResponse: +IEnumerable~Company~ Value
    CompaniesServiceResponse ..> Company: create

    class CredentialsServiceResponse
    CredentialsServiceResponse: +string No
    CredentialsServiceResponse: +string Password
    CredentialsServiceResponse: +string Name

    class FavJobModel
    FavJobModel: +string ressourceNo
    FavJobModel: +string jobNo

    class FavJobsModelResponse
    FavJobsModelResponse: +IEnumerable~FavJobModel~ Value
    FavJobsModelResponse ..> FavJobModel: create

    class JobModel
    JobModel: +string No
    JobModel: +string Description
    JobModel: +string Status
    JobModel: +bool AbsentDaysJob
    JobModel: +bool GeneralWorkJob
    JobModel: +bool GeneralFavourite

    class JobModelResponse
    JobModelResponse: +IEnumerable~JobModel~ Value
    JobModelResponse ..> JobModel: create

    class JobPlanningLinesModel
    JobPlanningLinesModel: +int LineNo
    JobPlanningLinesModel: +string Description
    JobPlanningLinesModel: +string JobTaskNo
    JobPlanningLinesModel: +string jobNo

    class JobPlanningLinesModelResponse
    JobPlanningLinesModelResponse: +IEnumerable~JobPlanningLinesModel~ Value
    JobPlanningLinesModelResponse ..> JobPlanningLinesModel: create

    class JobTasksModel
    JobTasksModel: +string JobTaskNo
    JobTasksModel: +string Description
    JobTasksModel: +string jobNo

    class JobTasksModelResponse
    JobTasksModelResponse: +IEnumerable~JobTasksModel~ Value
    JobTasksModelResponse ..> JobTasksModel: create

    class TimeRecording
    TimeRecording: +int id
    TimeRecording: +string JobNo
    TimeRecording: +string JobTaskNo
    TimeRecording: +string JobPlanningLineNo
    TimeRecording: +string RessourceNo
    TimeRecording: +DateTime? StartDateUTC
    TimeRecording: +TimeSpan? StartTimeUTC
    TimeRecording: +DateTime? EndDateUTC
    TimeRecording: +TimeSpan? EndTimeUTC
    TimeRecording: +double WorkHours
    TimeRecording: +string Type
    TimeRecording: +bool pause
    TimeRecording: +string note
    TimeRecording: +double timezone
    TimeRecording: +bool recordedManually

    class TimeRecordingResponse
    TimeRecordingResponse: +IEnumerable~TimeRecording~ TimeRecordings
    TimeRecordingResponse ..> TimeRecording: create

    class TypeOfAbsentDays
    TypeOfAbsentDays: +string TypeCode
    TypeOfAbsentDays: +string Description

    class TypeOfAbsentDaysResponse
    TypeOfAbsentDaysResponse ..> TypeOfAbsentDays: create
    TypeOfAbsentDaysResponse: +IEnumerable~TypeOfAbsentDays~ Value

    class AbsentDaysModel
    AbsentDaysModel ..> IJobService
    AbsentDaysModel ..> ITimeRecordingsService
    AbsentDaysModel ..> ITypeOfAbsentDaysService
    AbsentDaysModel ..> AppSession
    AbsentDaysModel: +IJobService _jobService
    AbsentDaysModel: +IEnumerable~JobModel~ JobModels
    AbsentDaysModel: +ITimeRecordingsService _timeRecordingsService
    AbsentDaysModel: +IEnumerable~TypeOfAbsentDays~ TypeOfAbsentDays
    AbsentDaysModel: +AppSession _ appSession
    AbsentDaysModel: +OnGet() IActionResult
    AbsentDaysModel: +OnPostLogOut() Task~IActionResult~
    AbsentDaysModel: +OnPostManual(TimeRecording request) Task~IActionResult~
    AbsentDaysModel: +GetResponseName() String
    AbsentDaysModel: +GetCompanyName() String
    AbsentDaysModel: -GetUsername()
    AbsentDaysModel: -GetCompanyID()
    AbsentDaysModel: +FormatWorkHours(TimeRecording item) String

    class AutomaticTimeRecordingModel
    AutomaticTimeRecordingModel ..> ITimeRecordingsService
    AutomaticTimeRecordingModel ..> ILocalTimeService
    AutomaticTimeRecordingModel ..> AppSession
    AutomaticTimeRecordingModel: +string _username
    AutomaticTimeRecordingModel: +string _name
    AutomaticTimeRecordingModel: +string _companyID
    AutomaticTimeRecordingModel: +ITimeRecordingsService _timeRecordingsService
    AutomaticTimeRecordingModel: +ILocalTimeService _localTimeService
    AutomaticTimeRecordingModel: +AppSession _ appSession
    AutomaticTimeRecordingModel: +IConfiguration _config
    AutomaticTimeRecordingModel: +OnGet() Task~IActionResult~
    AutomaticTimeRecordingModel: +OnPostLogOut() Task~IActionResult~
    AutomaticTimeRecordingModel: +OnPostStartTime(TimeRecording request) Task~IActionResult~
    AutomaticTimeRecordingModel: +OnPostEnd() Task~IActionResult~
    AutomaticTimeRecordingModel: -OnPostEndTime() Task
    AutomaticTimeRecordingModel: +OnPostPauseStart(TimeRecording request) Task~IActionResult~
    AutomaticTimeRecordingModel: +OnPostContinue(TimeRecording request) Task~IActionResult~
    AutomaticTimeRecordingModel: -OnPostPauseEnd(TimeRecording request) Task
    AutomaticTimeRecordingModel: +GetResponseName() String
    AutomaticTimeRecordingModel: +GetCompanyName() String
    AutomaticTimeRecordingModel: +GetUnstopped() Task~TimeRecording~
    AutomaticTimeRecordingModel: +GetUnstoppedPause() Task~TimeRecording~
    AutomaticTimeRecordingModel: +GetTodayTimeRecording() Task~TimeRecordingResponse~#
    AutomaticTimeRecordingModel: -GetCompanyID()
    AutomaticTimeRecordingModel: -GetUsername()
    AutomaticTimeRecordingModel: +GetInfos()

    class ChooseCompanyModel
    ChooseCompanyModel ..> AppSession
    ChooseCompanyModel ..> ICompaniesService
    ChooseCompanyModel: +AppSession _appSession
    ChooseCompanyModel: +ICompaniesService _companiesService
    ChooseCompanyModel: +IEnumerable~Company~ Companies
    ChooseCompanyModel: +bool ShowErrorMessage
    ChooseCompanyModel: +OnGet() Task~IActionResult~
    ChooseCompanyModel: +OnPost(Guid companyID) Task~IActionResult~

    class ChooseProjectModel
    ChooseProjectModel ..> IJobService
    ChooseProjectModel ..> IJobTasksService
    ChooseProjectModel ..> IJobPlanningLineService
    ChooseProjectModel ..> ITimeRecordingsService
    ChooseProjectModel ..> AppSession
    ChooseProjectModel: +string _username
    ChooseProjectModel: +IJobService _jobService
    ChooseProjectModel: +IJobTasksService _jobTasksService
    ChooseProjectModel: +IJobPlanningLineService _jobPlanningLineService
    ChooseProjectModel: +IEnumerable~JobModel~ JobModels
    ChooseProjectModel: +IEnumerable~JobTasksModel~ JobTasksModels
    ChooseProjectModel: +IEnumerable~JobPlanningLinesModel~ JobPlanningLinesModels
    ChooseProjectModel: +string jobNo
    ChooseProjectModel: +string jobTaskNo
    ChooseProjectModel: +DateTime dateTime
    ChooseProjectModel: +ITimeRecordingsService _timeRecordingsService
    ChooseProjectModel: +IEnumerable~TimeRecording~ timeRecordings
    ChooseProjectModel: +IConfiguration _config
    ChooseProjectModel: +string _companyID
    ChooseProjectModel: +AppSession _appSession
    ChooseProjectModel: +OnGet(DateTime date) Task~IActionResult~
    ChooseProjectModel: +OnPost(List~TimeRecording~ request) Task~RedirectToPageResult~
    ChooseProjectModel: +OnPostLogOut() Task~IActionResult~
    ChooseProjectModel: -GetCompanyID()
    ChooseProjectModel: -GetUsername()
    ChooseProjectModel: +GetResponseName() String
    ChooseProjectModel: +GetCompanyName() String

    class ChooseProjectRowModel
    ChooseProjectRowModel ..> IJobService
    ChooseProjectRowModel ..> AppSession
    ChooseProjectRowModel: +string companyID
    ChooseProjectRowModel: +string username
    ChooseProjectRowModel: +TimeRecording Item
    ChooseProjectRowModel: +IJobService JobService
    ChooseProjectRowModel: +IEnumerable~JobModel~ JobModels
    ChooseProjectRowModel: +AppSession _appSession
    ChooseProjectRowModel: +string ParentID
    ChooseProjectRowModel: +OnGetAsync(string start, string end, string parentID) Task

    class IndexModel
    IndexModel ..> AppSession
    IndexModel: +string _username
    IndexModel: +string _companyID
    IndexModel: +AppSession _appSession
    IndexModel: +OnGet() Task~IActionResult~
    
    class LoginModel
    LoginModel ..> ICredentialsService
    LoginModel ..> AppSession
    LoginModel: -ICredentialsService _credentialsService
    LoginModel: -string txt_loginError
    LoginModel: -AppSession _appSession
    LoginModel: +OnGetAsync(CredentialsServiceResponse request) Task~IActionResult~

    class ManualTimeRecordingModel
    ManualTimeRecordingModel ..> IJobService
    ManualTimeRecordingModel ..> ITimeRecordingsService
    ManualTimeRecordingModel ..> ITypeOfAbsentDaysService
    ManualTimeRecordingModel ..> AppSession
    ManualTimeRecordingModel: +string _username
    ManualTimeRecordingModel: +string _name
    ManualTimeRecordingModel: +string _companyID
    ManualTimeRecordingModel: +ITimeRecordingsService _timeRecordingsService
    ManualTimeRecordingModel: +IEnumerable~TimeRecording~ TimeRecordings
    ManualTimeRecordingModel: +IJobService _jobService
    ManualTimeRecordingModel: +IEnumerable~JobModel~ JobModels
    ManualTimeRecordingModel: +IConfiguration _config
    ManualTimeRecordingModel: +AppSession _appSession
    ManualTimeRecordingModel: +OnGet() IActionResult
    ManualTimeRecordingModel: +OnPostLogOut() Task~IActionResult~
    ManualTimeRecordingModel: +OnPostManual(TimeRecording request) Task~IActionResult~
    ManualTimeRecordingModel: +GetResponseName() String
    ManualTimeRecordingModel: +GetCompanyName() String
    ManualTimeRecordingModel: -GetUsername()
    ManualTimeRecordingModel: -GetCompanyID()
    ManualTimeRecordingModel: +FormatWorkHours(TimeRecording item) String

    class SetupModel
    SetupModel ..>ITimeRecordingsService
    SetupModel ..>IJobService
    SetupModel ..>AppSession
    SetupModel ..>FavJobRequest
    SetupModel: +string _username
    SetupModel: +string _name
    SetupModel: +string _companyID
    SetupModel: +FavJobsModelResponse favJobs
    SetupModel: +AppSession _appSession
    SetupModel: +ITimeRecordingsService _timeRecordingsService
    SetupModel: +IJobService _jobService
    SetupModel: +IConfiguration _config
    SetupModel: +OnGetAsync() Task~IActionResult~
    SetupModel: +OnPost(List~FavJobRequest~ request) Task~IActionResult~
    SetupModel: +GetResponseName() String
    SetupModel: +GetCompanyName() String
    SetupModel: -GetUsername()
    SetupModel: -GetCompanyID()
    SetupModel: +GetInfos()

    class FavJobRequest
    FavJobRequest: +string jobNo
    FavJobRequest: +bool fav
    FavJobRequest: +bool origFav

    class StatsModel
    StatsModel ..> ITimeRecordingsService
    StatsModel ..> AppSession
    StatsModel: +string _username
    StatsModel: +string _name
    StatsModel: +string _companyID
    StatsModel: +ITimeRecordingsService _timeRecordingsService
    StatsModel: +AppSession _appSession
    StatsModel: +List~IEnumerable< TimeRecording >~ sortedListsDays
    StatsModel: +List~IEnumerable< TimeRecording >~ sortedListsWeeks
    StatsModel: +List~IEnumerable< TimeRecording >~ sortedListsMonths
    StatsModel: +OnGetAsync() Task~IActionResult~
    StatsModel: +Sum(List~IEnumerable< TimeRecording >~ lists) double
    StatsModel: +SumAss(List~IEnumerable< TimeRecording >~ lists) double
    StatsModel: +SumNotAss(List~IEnumerable< TimeRecording >~ lists) double
    StatsModel: +SumAbs(List~IEnumerable< TimeRecording >~ lists) double
    StatsModel: +OnPostLogOut() Task~IActionResult~
    StatsModel: +GetInfos()
    StatsModel: +GetResponseName() string
    StatsModel: +GetCompanyName() string
    StatsModel: -GetCompanyID()
    StatsModel: -GetUsername()

    class TimeTableModel
    TimeTableModel ..> ITimeRecordingsService
    TimeTableModel ..> AppSession
    TimeTableModel: +string _username
    TimeTableModel: +string _name
    TimeTableModel: +string _companyID
    TimeTableModel: +ITimeRecordingsService _timeRecordingsService
    TimeTableModel: +IConfiguration _config
    TimeTableModel: +IEnumerable~TimeRecording~ timeRecordings
    TimeTableModel: +AppSession _appSession
    TimeTableModel: +OnGet() Task~IActionResult~
    TimeTableModel: +OnPostLogOut() Task~IActionResult~
    TimeTableModel: +GetInfos()
    TimeTableModel: +GetResponseName() string
    TimeTableModel: +GetCompanyName() string
    TimeTableModel: -GetUsername()
    TimeTableModel: -GetCompanyID()

    class Token
    Token ..> AppSession
    Token: +IConfiguration _config
    Token: +AppSession appSession
    Token: OnGet() JsonResult