
classDiagram
    class ICompaniesService
    <<interface>> ICompaniesService
    ICompaniesService: GetCompanies() Task~CompaniesServiceResponse~
    ICompaniesService: GetCompanyName(string companyId) Task~string~

    class ICredentialsService
    <<interface>> ICredentialsService
    ICredentialsService: GetCredentials(String Username, string companyID) Task~CredentialsServiceResponse~

    class IJobPlanningLineService
    <<interface>> IJobPlanningLineService
    IJobPlanningLineService: GetPlanningLines(string companyID, string jobNo, string jobTaskNo) Task~JobPlanningLinesModelResponse~

    class IJobService
    <<interface>> IJobService
    IJobService: GetJobs(string companyID, string username) Task~JobModelResponse~
    IJobService: GetFavJobsAsync(string companyID, string username) Task~FavJobsModelResponse~
    IJobService: PostFavJobAsync(FavJobModel request, string companyID)
    IJobService: DeleteFavJobsAsync(string id, string username, string companyID)

    class IJobTasksService
    <<interface>> IJobTasksService
    IJobTasksService: GetTasks(string companyID, string jobNo) Task~JobTasksModelResponse~

    class ILocalTimeService
    <<interface>> ILocalTimeService
    ILocalTimeService: GetLocalDateTime() DateTime
    ILocalTimeService: CalculateUTCDateTime(DateTime LocalDate) DateTime

    class ITimeRecordingsService
    <<interface>> ITimeRecordingsService
    ITimeRecordingsService: GetTimeRecordings(string companyID, string username) Task~TimeRecordingResponse~
    ITimeRecordingsService: PostTimeRecording(TimeRecording request, string companyID, int timezoneOffset) 
    ITimeRecordingsService: PatchTimeRecording(TimeRecording request, string companyID) 
    ITimeRecordingsService: DeleteTimeRecordings(int id, string companyID) 
    ITimeRecordingsService: GetUnstopped(string companyID, string username) Task~TimeRecording~
    ITimeRecordingsService: GetUnstoppedPause(string companyID, string username) Task~TimeRecording~
    ITimeRecordingsService: GetAllTimeRecordings(string companyID, string username) Task~TimeRecordingResponse~
    ITimeRecordingsService: GetTodayTimeRecordings(string companyID, string username) Task~TimeRecordingResponse~

    class ITypeOfAbsentDaysService
    <<interface>> ITypeOfAbsentDaysService
    ITypeOfAbsentDaysService: GetTypeOfAbsentDays(string companyID) Task~TypeOfAbsentDaysResponse~

    class CompaniesService
    CompaniesService ..> ICompaniesService
    CompaniesService: -string _baseURL
    CompaniesService: -string _apiEndpoint
    CompaniesService: -HttpClient client
    CompaniesService: -IAuthenticationService _authenticationService

    class CredentialsService
    CredentialsService ..> ICredentialsService
    CredentialsService: -string _baseURL
    CredentialsService: -string _apiEndpoint
    CredentialsService: -HttpClient client
    CredentialsService: -IAuthenticationService _authenticationService

    class JobPlanningLineService
    JobPlanningLineService ..> IJobPlanningLineService
    JobPlanningLineService: -string _baseURL
    JobPlanningLineService: -string _apiEndpointGet
    JobPlanningLineService: -string _apiEndpointGetWithParameter
    JobPlanningLineService: -HttpClient client
    JobPlanningLineService: -IAuthenticationService _authenticationService

    class JobService
    JobService ..> IJobService
    JobService: -string _baseURL
    JobService: -string _apiEndpointGet
    JobService: -string _apiEndpointGetFav
    JobService: -string _apiEndpointSetFav
    JobService: -HttpClient client
    JobService: -IAuthenticationService _authenticationService

    class JobTasksService
    JobTasksService ..> IJobTasksService
    JobTasksService: -string _baseURL
    JobTasksService: -string _apiEndpointGet
    JobTasksService: -HttpClient client
    JobTasksService: -IAuthenticationService _authenticationService

    class LocalTimeService
    LocalTimeService ..> ILocalTimeService
    LocalTimeService: -int TimeZoneOffset
    LocalTimeService: -IHttpContextAccessor _httpContextAccessor
    LocalTimeService: -GetTimeZoneOffset()

    class TimeRecordingsService
    TimeRecordingsService ..> ITimeRecordingsService
    TimeRecordingsService ..> ILocalTimeService
    TimeRecordingsService: -string _baseURL
    TimeRecordingsService: -string _apiEndpointGet
    TimeRecordingsService: -string _apiEndpointSet
    TimeRecordingsService: -string _apiEndpointGetToday
    TimeRecordingsService: -string _apiEndpointUnstopped
    TimeRecordingsService: -string _apiEndpointUnstoppedPause
    TimeRecordingsService: -HttpClient client
    TimeRecordingsService: -IAuthenticationService _authenticationService
    TimeRecordingsService: -ILocalTimeService _localTimeService
    TimeRecordingsService: -GetDates(String companyID, string username) Task~String~

    class TypeOfAbsentDaysService
    TypeOfAbsentDaysService ..> ITypeOfAbsentDaysService
    TypeOfAbsentDaysService: -string _baseURL
    TypeOfAbsentDaysService: -string _apiEndpointGet
    TypeOfAbsentDaysService: -HttpClient client
    TypeOfAbsentDaysService: -IAuthenticationService _authenticationService