classDiagram
    class ITimeRecordingsService
    <<interface>> ITimeRecordingsService
    ITimeRecordingsService: GetTimeRecordings(string companyID, string username) Task~TimeRecordingResponse~
    ITimeRecordingsService: PostTimeRecording(TimeRecording request, string companyID, int timezoneOffset) 
    ITimeRecordingsService: PatchTimeRecording(TimeRecording request, string companyID) 
    ITimeRecordingsService: DeleteTimeRecordings(int id, string companyID) 
    ITimeRecordingsService: GetUnstopped(string companyID, string username) Task~TimeRecording~
    ITimeRecordingsService: GetUnstoppedPause(string companyID, string username) Task~TimeRecording~
    ITimeRecordingsService: GetAllTimeRecordings(string companyID, string username) Task~TimeRecordingResponse~
    ITimeRecordingsService: GetTodayTimeRecordings(string companyID, string username) Task~TimeRecordingResponse~

    class AbsentDaysModel
    AbsentDaysModel ..> ITimeRecordingsService
    AbsentDaysModel: +IJobService _jobService
    AbsentDaysModel: +IEnumerable~JobModel~ JobModels
    AbsentDaysModel: +ITimeRecordingsService _timeRecordingsService
    AbsentDaysModel: +IEnumerable~TypeOfAbsentDays~ TypeOfAbsentDays
    AbsentDaysModel: +AppSession _ appSession
    AbsentDaysModel: +OnGet() IActionResult
    AbsentDaysModel: +OnPostLogOut() Task~IActionResult~
    AbsentDaysModel: +OnPostManual(TimeRecording request) Task~IActionResult~
    AbsentDaysModel: +GetResponseName() String
    AbsentDaysModel: +GetCompanyName() String
    AbsentDaysModel: -GetUsername()
    AbsentDaysModel: -GetCompanyID()
    AbsentDaysModel: +FormatWorkHours(TimeRecording item) String

    class AutomaticTimeRecordingModel
    AutomaticTimeRecordingModel ..> ITimeRecordingsService
    AutomaticTimeRecordingModel: +string _username
    AutomaticTimeRecordingModel: +string _name
    AutomaticTimeRecordingModel: +string _companyID
    AutomaticTimeRecordingModel: +ITimeRecordingsService _timeRecordingsService
    AutomaticTimeRecordingModel: +ILocalTimeService _localTimeService
    AutomaticTimeRecordingModel: +AppSession _ appSession
    AutomaticTimeRecordingModel: +IConfiguration _config
    AutomaticTimeRecordingModel: +OnGet() Task~IActionResult~
    AutomaticTimeRecordingModel: +OnPostLogOut() Task~IActionResult~
    AutomaticTimeRecordingModel: +OnPostStartTime(TimeRecording request) Task~IActionResult~
    AutomaticTimeRecordingModel: +OnPostEnd() Task~IActionResult~
    AutomaticTimeRecordingModel: -OnPostEndTime() Task
    AutomaticTimeRecordingModel: +OnPostPauseStart(TimeRecording request) Task~IActionResult~
    AutomaticTimeRecordingModel: +OnPostContinue(TimeRecording request) Task~IActionResult~
    AutomaticTimeRecordingModel: -OnPostPauseEnd(TimeRecording request) Task
    AutomaticTimeRecordingModel: +GetResponseName() String
    AutomaticTimeRecordingModel: +GetCompanyName() String
    AutomaticTimeRecordingModel: +GetUnstopped() Task~TimeRecording~
    AutomaticTimeRecordingModel: +GetUnstoppedPause() Task~TimeRecording~
    AutomaticTimeRecordingModel: +GetTodayTimeRecording() Task~TimeRecordingResponse~#
    AutomaticTimeRecordingModel: -GetCompanyID()
    AutomaticTimeRecordingModel: -GetUsername()
    AutomaticTimeRecordingModel: +GetInfos()

    class ChooseProjectModel
    ChooseProjectModel ..> ITimeRecordingsService
    ChooseProjectModel: +string _username
    ChooseProjectModel: +IJobService _jobService
    ChooseProjectModel: +IJobTasksService _jobTasksService
    ChooseProjectModel: +IJobPlanningLineService _jobPlanningLineService
    ChooseProjectModel: +IEnumerable~JobModel~ JobModels
    ChooseProjectModel: +IEnumerable~JobTasksModel~ JobTasksModels
    ChooseProjectModel: +IEnumerable~JobPlanningLinesModel~ JobPlanningLinesModels
    ChooseProjectModel: +string jobNo
    ChooseProjectModel: +string jobTaskNo
    ChooseProjectModel: +DateTime dateTime
    ChooseProjectModel: +ITimeRecordingsService _timeRecordingsService
    ChooseProjectModel: +IEnumerable~TimeRecording~ timeRecordings
    ChooseProjectModel: +IConfiguration _config
    ChooseProjectModel: +string _companyID
    ChooseProjectModel: +AppSession _appSession
    ChooseProjectModel: +OnGet(DateTime date) Task~IActionResult~
    ChooseProjectModel: +OnPost(List~TimeRecording~ request) Task~RedirectToPageResult~
    ChooseProjectModel: +OnPostLogOut() Task~IActionResult~
    ChooseProjectModel: -GetCompanyID()
    ChooseProjectModel: -GetUsername()
    ChooseProjectModel: +GetResponseName() String
    ChooseProjectModel: +GetCompanyName() String

    class ManualTimeRecordingModel
    ManualTimeRecordingModel ..> ITimeRecordingsService
    ManualTimeRecordingModel: +string _username
    ManualTimeRecordingModel: +string _name
    ManualTimeRecordingModel: +string _companyID
    ManualTimeRecordingModel: +ITimeRecordingsService _timeRecordingsService
    ManualTimeRecordingModel: +IEnumerable~TimeRecording~ TimeRecordings
    ManualTimeRecordingModel: +IJobService _jobService
    ManualTimeRecordingModel: +IEnumerable~JobModel~ JobModels
    ManualTimeRecordingModel: +IConfiguration _config
    ManualTimeRecordingModel: +AppSession _appSession
    ManualTimeRecordingModel: +OnGet() IActionResult
    ManualTimeRecordingModel: +OnPostLogOut() Task~IActionResult~
    ManualTimeRecordingModel: +OnPostManual(TimeRecording request) Task~IActionResult~
    ManualTimeRecordingModel: +GetResponseName() String
    ManualTimeRecordingModel: +GetCompanyName() String
    ManualTimeRecordingModel: -GetUsername()
    ManualTimeRecordingModel: -GetCompanyID()
    ManualTimeRecordingModel: +FormatWorkHours(TimeRecording item) String

    class SetupModel
    SetupModel ..>ITimeRecordingsService
    SetupModel: +string _username
    SetupModel: +string _name
    SetupModel: +string _companyID
    SetupModel: +FavJobsModelResponse favJobs
    SetupModel: +AppSession _appSession
    SetupModel: +ITimeRecordingsService _timeRecordingsService
    SetupModel: +IJobService _jobService
    SetupModel: +IConfiguration _config
    SetupModel: +OnGetAsync() Task~IActionResult~
    SetupModel: +OnPost(List~FavJobRequest~ request) Task~IActionResult~
    SetupModel: +GetResponseName() String
    SetupModel: +GetCompanyName() String
    SetupModel: -GetUsername()
    SetupModel: -GetCompanyID()
    SetupModel: +GetInfos()

    class StatsModel
    StatsModel ..> ITimeRecordingsService
    StatsModel: +string _username
    StatsModel: +string _name
    StatsModel: +string _companyID
    StatsModel: +ITimeRecordingsService _timeRecordingsService
    StatsModel: +AppSession _appSession
    StatsModel: +List~IEnumerable< TimeRecording >~ sortedListsDays
    StatsModel: +List~IEnumerable< TimeRecording >~ sortedListsWeeks
    StatsModel: +List~IEnumerable< TimeRecording >~ sortedListsMonths
    StatsModel: +OnGetAsync() Task~IActionResult~
    StatsModel: +Sum(List~IEnumerable< TimeRecording >~ lists) double
    StatsModel: +SumAss(List~IEnumerable< TimeRecording >~ lists) double
    StatsModel: +SumNotAss(List~IEnumerable< TimeRecording >~ lists) double
    StatsModel: +SumAbs(List~IEnumerable< TimeRecording >~ lists) double
    StatsModel: +OnPostLogOut() Task~IActionResult~
    StatsModel: +GetInfos()
    StatsModel: +GetResponseName() string
    StatsModel: +GetCompanyName() string
    StatsModel: -GetCompanyID()
    StatsModel: -GetUsername()

    class TimeTableModel
    TimeTableModel ..> ITimeRecordingsService
    TimeTableModel: +string _username
    TimeTableModel: +string _name
    TimeTableModel: +string _companyID
    TimeTableModel: +ITimeRecordingsService _timeRecordingsService
    TimeTableModel: +IConfiguration _config
    TimeTableModel: +IEnumerable~TimeRecording~ timeRecordings
    TimeTableModel: +AppSession _appSession
    TimeTableModel: +OnGet() Task~IActionResult~
    TimeTableModel: +OnPostLogOut() Task~IActionResult~
    TimeTableModel: +GetInfos()
    TimeTableModel: +GetResponseName() string
    TimeTableModel: +GetCompanyName() string
    TimeTableModel: -GetUsername()
    TimeTableModel: -GetCompanyID()