
classDiagram
    class Program
    Program: +CreateHostBuilder()
    Program ..> StartUp : create

    class StartUp
    StartUp ..> BCWebApiServiceCollectionExtension : uses
    StartUp ..> AppSession : creates
    StartUp: -HttpClient _client
    StartUp: +ConfigureService(IServiceCollection services)
    StartUp: +Configure(IApplicationBuilder app, IWebHostEnvironment env)

    class BCWebApiServiceCollectionExtension
    BCWebApiServiceCollectionExtension: +AddBCWebApiServices(this IServiceCollection services)
    BCWebApiServiceCollectionExtension: -AddBCWebApiAuthenticationService(this IServiceCollection services)

    class AppSession
    AppSession: +ISession Session
    AppSession: +string ContactNo
    AppSession: +string CompanyID
    AppSession: +string sessionToken
    AppSession: +int timeZoneOffset
    AppSession: +Clear()
    AppSession: +Check() Boolean